import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';
import { CelldPlugin } from '../src/lib/build-plugin-celld.ts';
import type { BuildContext } from '../src/lib/types.ts';

describe('CelldPlugin', () => {
	it('generates the same Durable Object identities as the Cloudflare target', async () => {
		const entry = await new CelldPlugin().generateEntryPoint(
			testBuildContext({
				agents: [{ name: 'draft-workflow', filePath: '/fixture/agents/draft-workflow.ts' }],
				workflows: [{ name: 'draft', filePath: '/fixture/workflows/draft.ts' }],
			}),
		);

		expect(entry).toContain('// Auto-generated by flue (target: celld)');
		expect(entry).toContain('class FlueDraftWorkflowAgent');
		expect(entry).toContain('class FlueDraftWorkflow');
		expect(entry).toContain('bindingName: "FLUE_DRAFT_WORKFLOW_AGENT"');
		expect(entry).toContain('bindingName: "FLUE_DRAFT_WORKFLOW"');
	});

	it('omits Vite-specific import.meta.env from the generated entry', async () => {
		// celld deploys through its own esbuild step, where import.meta.env is
		// undefined — evaluating `.DEV` on it would throw at module load.
		const entry = await new CelldPlugin().generateEntryPoint(testBuildContext());

		expect(entry).not.toContain('import.meta.env');
		expect(entry).toContain('devMode: false,');
	});

	it('registers the Workers AI provider only when an AI binding exists', async () => {
		// celld fleets have no AI binding unless the operator wires the
		// experimental CELLD_AI_URL adapter.
		const entry = await new CelldPlugin().generateEntryPoint(testBuildContext());

		expect(entry).toContain(`if (env.AI && !hasRegisteredProvider('cloudflare')) {`);
	});

	it('rejects db.ts custom persistence', async () => {
		await expect(
			new CelldPlugin().generateEntryPoint(testBuildContext({ dbEntry: '/fixture/db.ts' })),
		).rejects.toThrow('Custom persistence (db.ts) is not supported on the celld target');
	});

	it('writes a celld-subset wrangler config pointing at the generated entry', async () => {
		const root = createFixtureRoot({
			'wrangler.jsonc': JSON.stringify({
				name: 'my-agents',
				compatibility_date: '2026-06-01',
				migrations: [{ tag: 'v1', new_sqlite_classes: ['FlueAssistantAgent'] }],
			}),
		});

		const inputs = await new CelldPlugin().viteInputs(
			testBuildContext({
				root,
				agents: [{ name: 'assistant', filePath: path.join(root, 'agents', 'assistant.ts') }],
			}),
		);
		const config = JSON.parse(inputs.wranglerConfig);

		expect(config.main).toBe('./_entry.ts');
		expect(config.name).toBe('my-agents');
		expect(config.$schema).toBeUndefined();
		expect(config.compatibility_date).toBe('2026-06-01');
		expect(config.migrations).toEqual([{ tag: 'v1', new_sqlite_classes: ['FlueAssistantAgent'] }]);
		expect(config.durable_objects.bindings).toEqual([
			{ name: 'FLUE_ASSISTANT_AGENT', class_name: 'FlueAssistantAgent' },
			{ name: 'FLUE_REGISTRY', class_name: 'FlueRegistry' },
		]);
	});

	it('defaults name and compatibility settings when no wrangler config exists', async () => {
		const root = createFixtureRoot({});

		const inputs = await new CelldPlugin().viteInputs(testBuildContext({ root }));
		const config = JSON.parse(inputs.wranglerConfig);

		expect(config.name).toBe(path.basename(root));
		expect(config.compatibility_date).toBe('2026-04-01');
		expect(config.compatibility_flags).toEqual(['nodejs_compat']);
		expect(config.durable_objects.bindings).toEqual([
			{ name: 'FLUE_REGISTRY', class_name: 'FlueRegistry' },
		]);
	});

	it('rejects wrangler config keys celld does not support', async () => {
		const root = createFixtureRoot({
			'wrangler.jsonc': JSON.stringify({ kv_namespaces: [{ binding: 'CACHE', id: 'x' }] }),
		});

		await expect(new CelldPlugin().viteInputs(testBuildContext({ root }))).rejects.toThrow(
			'celld does not support: kv_namespaces',
		);
	});

	it('rejects a wrangler.toml config', async () => {
		const root = createFixtureRoot({ 'wrangler.toml': 'name = "my-agents"\n' });

		await expect(new CelldPlugin().viteInputs(testBuildContext({ root }))).rejects.toThrow(
			'celld accepts wrangler.jsonc or wrangler.json, not wrangler.toml',
		);
	});

	it('absolutizes a root-relative assets directory for the deploy directory', async () => {
		const root = createFixtureRoot({
			'wrangler.jsonc': JSON.stringify({ assets: { directory: './public' } }),
		});

		const inputs = await new CelldPlugin().viteInputs(testBuildContext({ root }));
		const config = JSON.parse(inputs.wranglerConfig);

		expect(config.assets.directory).toBe(path.resolve(root, 'public').replace(/\\/g, '/'));
	});
});

function testBuildContext(overrides: Partial<BuildContext> = {}): BuildContext {
	return {
		agents: [],
		workflows: [],
		channels: [],
		root: '/fixture',
		output: '/fixture/dist',
		log: 'silent',
		...overrides,
	};
}

function createFixtureRoot(files: Record<string, string>): string {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), 'flue-celld-'));
	for (const [name, content] of Object.entries(files)) {
		fs.writeFileSync(path.join(root, name), content);
	}
	return root;
}
